# Site Settings
baseurl: ""
url: "https://tave-6th-rlstudy.github.io/"
google_analytics: UA-164515885-2

# Blog Settings
theme_settings:
  title: TAVE 6TH RL Stydy
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/smile.png
    username: TAVE 6기 강화학습팀
    description: 간단한 설명
    experience:
      - start: 2020-08-13
        end:
        experience: TAVE, Reinforcement Learning
    skills:
      - skill: STUDY & PROJECTS
        value: 5 # Percent value
    teammember:
      - name1: 영어이름 , 영어이름
      - name2: blah
      - name3: blah

  # Icons
  icons:
    email: leo503801@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: # Full URL
    github: TAVE-6th-RLstudy
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
