# Site Settings
baseurl: ""
url: "https://tave-6th-rlstudy.github.io/"
google_analytics: UA-164515885-2

# Blog Settings
theme_settings:
  title: TAVE 6기 강화학습 스터디
  description: Reinforcement Learning
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/smile.png
    username: TAVE 6기 강화학습팀
    description: Reinforcement Learning Study&Project
    experience:
      - start: 2020-08-13
        end:
        experience: TAVE 6TH, First Half(RL Study)
    skills:
      - skill: STUDY
        value: 83 # Percent value
    teammember:
      - name1: Park Jeiyoon | Lee Moonki
      - name2: Lim Sooyeon   | Cho Jaehoon
      - name3: Lee Sangwon  | Park Yewon

  # Icons
  icons:
    email: leo503801@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: # Full URL
    github: TAVE-6th-RLstudy
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname: "tave-6th-rlstudy.github.io"

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
